on:
  push:
    branches:
      - master
      - school
name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.29.2'
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outpus/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}